### ISSUE TITLE
Optional fields original index bug

### ISSUE THREAD

**Issue by GlaDOSik** [CloseITsro/pdi-sas-reader#3]
Optional fields aren't skipped due to wrong condition. Also optional fields are missing in the stream which can be a problem because the row length can differ from file to file. Missing optional fields should have null in the row.

**Comment by tkaszuba** [comment]
Issue was still open as we need to check against the length and not length - 1 but now it should be fixed.

**Comment by GlaDOSik** [comment]
Thanks. I had to be blind.
